apiVersion: v1
kind: ConfigMap
metadata:
  name: gesture-listener-config
data:
  config.json: |
    {
    "amqp": {
        "host": "10.20.5.1",
        "port": 30000,
        "user": "guest",
        "password": "guest"
    },
    "topic": "Gesture.0.Detection",
    "gesture_rpc_mapping": {
        "Ask for help": "Agent.Environment.Labvisio.Activate"
    }
    }
