apiVersion: v1
kind: Service
metadata:
  name: gesture-listener
  labels:
    app: gesture-listener
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32503
      protocol: TCP
      name: http
  selector:
    app: gesture-listener
